apiVersion: v1
kind: Pod
metadata:
  name: docker-challenge
  namespace: test
  labels:
    app: docker-challenge
    version: v1
spec:
  containers:
    - name: docker-challenge
      image: marziehvahid/docker-challenge:latest
      ports:
        - name: web
          containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["sleep", "15"]