apiVersion: v1
kind: Service
metadata:
  name: docker-challenge-svc
  namespace: test
  labels:
    app: docker-challenge
spec:
  type: NodePort
  selector:
    app: docker-challenge
  ports:
    - protocol: TCP
      port: 80
      name: http
